### ISSUE TITLE
Node unable to create valid public erc55 key in existing wallets

### ISSUE THREAD

**Issue by Black-Dragonking** [DeFiCh/ain#2604] opened 2023-10-22 14:29 UTC
## Summary

- transferdomain 3->2 result in error: no valid public key for address 0x96....

## Steps to Reproduce
use an existing wallet

1. create own adress:
- getnewaddress "Metamask" erc55
- getaddressinfo -> "ismine": true
- transferdomain 1 DFI from 2 to 3 OK
- transferdomain 1 DFI frim 3 to 2 : no valid public key for address

2. import Privkey from metamask
- importprivkey "..." "MetamaskTestnet" true
- getaddressinfo -> "ismine": true
- transferdomain 1 DFI from 2 to 3 OK
- transferdomain 1 DFI frim 3 to 2 : no valid public key for address

## Environment

[Please fill all of the following or NA if not applicable]

- Node Version: 4.0.0
- Block height on bug if applicable: 
- TX or TX type on bug if applicable:  
- OS with version: Windows 10
- Any other relevant environment info:

**Comment by kuegi** [comment] 2023-10-22 14:50
I can reproduce it with old wallet. creating a fresh wallet and importing the same private keys works.

on the new wallet, getaddressinfo has additional `desc` entry and the pubkey is longer and starts with 04

**Comment by DeFiPages** [comment] 2023-10-22 17:23
My testnet wallet, created in January '23 with some masternode addresses, worked in changi and is also functioning in the rolled-back testnet.
I just imported a private key of a metamask address (0x..)
```
defi-cli -testnet getaddressinfo 0x...
{
...
 "desc": "addr(0x.....)#gz4gwdtf",
...
  "pubkey": "042
...
}
```
transferdomain from 0x... to dvm address work without error.

**Comment by prasannavl** [comment] 2023-10-23 03:16
This is currently intended, though has to be migrated on the long term. 

What's currently supported: things should work seamlessly if addressmap can show it. You didn't add the addressmap output, but I'd assume it would show as it doesn't know. 

Rationale: 

- The only way to get into this place is for advanced enough users who already understand the key process, since otherwise, there's no way to get the address mapping (things like addressmap won't actually return one either). 

Reason: 

- Old keys don't have the indexes for the ERC55 entries. We don't automatically add them, as it'll blow up your wallets with a lot more entries suddenly and any accidental corruption due to external factors (process killed or any such reason) in the migration process can result in a potential disaster. 

Long term plan: Migrate the wallet in one of the next upgrades, so it's add the old keys as well, but has to be done carefully with backups.

**Comment by prasannavl** [comment] 2023-10-23 04:15
That being said, there's a different (unrelated, but close) input processing bug on addressmap RPC. Will get that fixed now.

**Comment by kuegi** [comment] 2023-10-23 05:55
@prasannavl I don't fully understand. I get the "don't automatically upgrade all old addresses", but I did fresh importprivkey calls for the addresses.
`addressmap` gives me correct output. Still the transferdomain only works in one direction.

It only works when I create a new wallet.dat and import there. IMHO it should work with addresses that get reimported (and of course newly generated addresses in an old wallet).

Just reconfirmed:
* reimport priv key of existing bech32 address `address1`
* importprivkey of MM address `address2` (wasn't in the wallet before)
-> `transferdomain [{"src":{"address":"address2","amount":"1@DFI","domain":3},"dst":{"address":"address1","amount":"1@DFI","domain":2}}]` fails

You are right `addressmap address2 0` also gives the error (both for the ERC55 from MM and for the ERC55 version of address1)

So is it intended that you have to create a new wallet.dat and can not use evm->dvm transfer with old wallet.dat ? or is the missing public key even after fresh import a bug?

**Comment by prasannavl** [comment] 2023-10-23 06:39
>  or is the missing public key even after fresh import a bug?

This would be the bug if this is case

 cc/ @Bushstar

**Comment by Bushstar** [comment] 2023-10-23 07:33
@kuegi the old wallet where you see the pubkeys starting with 02, is it encrypted?

**Comment by kuegi** [comment] 2023-10-23 07:59
@Bushstar yes, and the new wallet that I created for testing wasn't.
Based on that I also did a quick check: if I take the wallet from before (where addressmap ... 0 works) and encrypt it, afterwards `addressmap` doesn't find the public key anymore. So it only works with unencrypted wallets?

**Comment by Bushstar** [comment] 2023-10-23 08:03
The issue appears to be encrypted wallets rather than old wallets. Investigating now and will work on an update.

**Closed** 2023-10-24 05:13 UTC
Labels: bug
