### ISSUE TITLE
Official Wallet Snapshot on wrong chain

### ISSUE THREAD

**Issue by Stonygan** [DeFiCh/ain#2701] opened 2023-11-17 21:51 UTC
## Summary
The last Snapshot from today, maybe from yesterday, too is on wrong chain.
https://defi-snapshots-europe.s3.eu-central-1.amazonaws.com/index.txt

snapshot-mainnet-3462289.zip

It seems the node is hanging since yesterday. Update of Defichain Dsktop wallet with Snapshot not possible.

`3462289 = 3f652cb52a387c30ed15d574d258e61ef8b9d22203a643ef9e1e6991b66f6192`

**Comment by prasannavl** [comment] 2023-11-18 00:19
Thanks. The snapshot server was intentionally turned off for the weekend pending update. But seems there was a zombie running that got 2 3.2.8 snapshots in. 

Cleaning it up shortly.

**Comment by prasannavl** [comment] 2023-11-18 00:55
Resolved. Please re-download snapshot and should get things moving now. 

The latest snapshot are currently 2 days old, so will still catch up a bit. Newer snapshots should be available soon again next week.

**Comment by supervolot** [comment] 2023-11-18 20:28
Hi, I've been trying in vain to update my nodes since yesterday and was getting desperate. Can you please communicate such failures better so that you can avoid a lot of frustration among users. PS why does it take so long to create a new snapshot?

**Comment by bernd-mack** [comment] 2023-11-18 23:23
2023-11-18T23:16:01Z ERROR: AcceptBlockHeader: block 2886b9d94e6e32af7af0d8e1da4c23427c0b51131a646d49ed135b46ca7c39e1 is marked invalid
2023-11-18T23:17:31Z ERROR: ConnectBlock 2886b9d94e6e32af7af0d8e1da4c23427c0b51131a646d49ed135b46ca7c39e1 failed, bad-custom-tx (code 68)

I just rebooted my system and loaded the current snapshot. it ends in an invalid block which I can't get into my local chain even with reconsider. In the masternode group, the problems of the users are also increasing. It seems as if the snapshots can no longer be created in the usual way since the hardfork and lead to errors when reimported.

**Comment by supervolot** [comment] 2023-11-19 12:17
My nodes also stuck, even with the new snapshot form 18.11.

**Comment by Stonygan** [comment] 2023-11-19 13:04
https://github.com/DeFiCh/ain/issues/2705

**Comment by prasannavl** [comment] 2023-11-19 13:52
Could you clarify - are we still talking about node or the wallet app? 

The latest snapshot available is [snapshot-mainnet-3461101](https://defi-snapshots-europe.s3.eu-central-1.amazonaws.com/snapshot-mainnet-3461101.zip)

Could you clarify what snapshots you're on? 

> It seems as if the snapshots can no longer be created in the usual way since the hardfork and lead to errors when reimported.

Could you elaborate what you mean? As long as the whole datadir is backed-up, snapshotting should be the same as before.

**Comment by Stonygan** [comment] 2023-11-19 15:34
No matter, both are affected. Its related point 1 because the node recognizes blocks as invalid after restart as described in #2705 i think. Maybe we wait if you can create new snapshots next week after hardforkblock. point 2: i try your snapshot above with desktop Wallet, but atm its difficult to connect to correct chain, because "some" other chains are forked at Hardforkblock and v4 dont reject them and syncing stopped on older chain, normal users cant handle this with invalidate/reconsider, see @bernd-mack comment.

**Comment by prasannavl** [comment] 2023-11-19 23:22
From the snapshot (specifically [snapshot-mainnet-3461101](https://defi-snapshots-europe.s3.eu-central-1.amazonaws.com/snapshot-mainnet-3461101.zip)), there shouldn't be no need to reconsider. If you're seeing this, would appreciate full debug.log file on this, and I am not able to reproduce this. I can see that it lands on the correctly. 

We'll look deeper to see if restarts are adding to this somehow.

**Comment by prasannavl** [comment] 2023-11-19 23:22
Re-opening until clarification.

**Comment by Stonygan** [comment] 2023-11-20 01:37
2023-11-19T15:19:06Z UpdateTip: new best=**03868e658929a14be101b530bfed3ef665966613aa4f8c33f3eead4c2ffacf86** height=**3462112** version=0x20000000 log2_work=87.939121 tx=27112883 date='2023-11-16T08:45:55Z' progress=0.998083 cache=0.2MiB(1046txo)
2023-11-19T15:19:35Z UpdateTip: new best=ac8b0c4eaf94c200f66e3be918f5d50a4ed74a92e7dd803cea4c4626c94a786f height=3462149 version=0x20000000 log2_work=87.939128 tx=27113770 date='2023-11-16T09:27:30Z' progress=0.998100 cache=0.2MiB(1383txo)
2023-11-19T15:19:58Z UpdateTip: new best=d0d0965d5c70667da75c16892f90b7bd27a8f7449080ad4fb091811d35976eb9 height=3462151 version=0x20000000 log2_work=87.939129 tx=27114091 date='2023-11-16T09:46:31Z' progress=0.998107 cache=0.2MiB(1495txo)
2023-11-19T15:20:36Z UpdateTip: new best=200475714f15ba3158872ccbc26e9c8602371f20704c307e16b2a5f181afa836 height=3462158 version=0x20000000 log2_work=87.93913 tx=27114683 date='2023-11-16T10:53:36Z' progress=0.998134 cache=0.3MiB(1824txo)
2023-11-19T15:21:01Z UpdateTip: new best=c62fcc1d22d3c245819a5f02ee3a21d4d4b2a3ffcbf276710c243a0c6e4bfcc1 height=3462165 version=0x20000000 log2_work=87.939132 tx=27115396 date='2023-11-16T11:59:31Z' progress=0.998161 cache=0.3MiB(2242txo)
2023-11-19T15:21:24Z UpdateTip: new best=**03868e658929a14be101b530bfed3ef665966613aa4f8c33f3eead4c2ffacf86** height=**3462173** version=0x20000000 log2_work=87.939133 tx=27116107 date='2023-11-16T13:40:56Z' progress=0.998202 cache=0.5MiB(4173txo)

Thats strange that 1 hash in 2 blocks the same. Rollback happened here. Database is corrupt now, can't give more details.

**Comment by supervolot** [comment] 2023-11-20 07:16
i have the problem with my tow windows desktop app´s.

**Comment by prasannavl** [comment] 2024-05-17 16:58
There has been a few refinements to the EVM database in the later versions. Is this issue resolved in later versions or do you still continue to experience this?

**Closed** 2024-07-15 19:19 UTC
Labels: bug
