### ISSUE TITLE
Decode failed for special Tx in mempool

### ISSUE THREAD

**Issue by Darkchicken1991** [DeFiCh/ain#1747] opened 2023-02-08 13:12 UTC
On Block 2657248 i got this Transaction in my Mempool. I tried to decode it with "decodecustomtx" but after a bad request my node crashed.

04000000000101f27d887935293ba6896919abada52efabe427059f97d002e099182f044ff9ba10000000000ffffffff0200d0ed902e000000e76a4ce4446654787a0116001481c7d435eea178096f8104f2585d2f7d5d0aca8b0040e59c3012000001534346503a204f6e676f696e6720496e7665737469676174696f6e2f436173652041746f6d696320537761702d64425443204578706c6f6974206f6e2044654669436861696e202d2042756467657420323032336768747470733a2f2f7777772e7265646469742e636f6d2f722f64656669626c6f636b636861696e2f636f6d6d656e74732f313077727274322f6366705f6f6e676f696e675f696e7665737469676174696f6e636173655f61746f6d69635f73776170646274632f000000a0b2c4040000000016001481c7d435eea178096f8104f2585d2f7d5d0aca8b000247304402203a775b0dcdf9b76e4b45bee8ed93fa051a981256b364fe83502ddc0c1cd6835e022017956a89850ce54c35f880e7106529e32faeaea266f175a20ded06276375d72b012103c2e88d7ec7df6bc667f091510d6a43f961c5a4004d5d165d260a91f2bea4899600000000

**Comment by kuegi** [comment] 2023-02-09 06:40
@Darkchicken1991 are you running 3.2.3 ? sounds like a duplicate of #1739 which is fixed in 3.2.4

**Comment by Bushstar** [comment] 2023-02-09 12:32
It is the same as the issue linked in @kuegi above which has been resolved in the 3.2.4 release with the following fix.

https://github.com/DeFiCh/ain/pull/1742

**Closed by Bushstar** 2023-02-09 12:32 UTC
Labels: kind/bug, needs/triage
