### ISSUE TITLE
transferdomain creates a transaction although input data is missing (empty array)

### ISSUE THREAD

**Issue by bernd-mack** [DeFiCh/ain#2158] opened 2023-07-05 10:42 UTC
## Summary

the check for empty input does not check for empty array at transferdomain command.

## Steps to Reproduce

```
.defi/defi-cli transferdomain []
4b280e6c96fc3fa5844ae0afaac669f51c4a0f27c93ed5e47da0c25d0a447f4f
```

## Environment

- Node Version:  changi beta4
- Block height on bug if applicable: n/a
- TX or TX type on bug if applicable:  4b280e6c96fc3fa5844ae0afaac669f51c4a0f27c93ed5e47da0c25d0a447f4f
- OS with version: linux, windows
- Any other relevant environment info:  n/a

**Comment by prasannavl** [comment] 2023-07-05 10:59
Thanks for the report. There has been quite a lot of changes since last week. https://github.com/DeFiCh/ain/pull/2124 already should have fixed this and a few others. 

We should have network upgrade in the next 24-48 hours with all of this rolled in.

**Comment by shohamc1** [comment] 2023-07-20 07:03
This should be fixed as in beta5. Feel free to reopen this issue if you can reproduce the issue on beta5.

**Closed by shohamc1** 2023-07-20 07:03 UTC
Labels: bug

**Comment by bernd-mack** [comment] 2023-07-21 14:58
seems as if it is activated, then this errormessage makes no sense
```
.defi/defi-cli transferdomain []
error code: -32600
error message:
Test TransferDomainTx execution failed:
Cannot create tx, transfer domain is not enabled
```

**Comment by bernd-mack** [comment] 2023-07-21 19:40
```
.defi/defi-cli transferdomain []
error code: -32600
error message:
Test TransferDomainTx execution failed:
TransferDomain currently only supports a single transfer per transaction
```

i would expect to return same as if there is no parameter:
```
.defi/defi-cli transferdomain
error code: -1
error message:
transferdomain [{"src":obj,"dst":obj},...]
Creates (and submits to local node and network) a tx to transfer balance from DFI/ETH address to DFI/ETH address.


Arguments:
1. array                        (json array, required) A json array of src and dst json objects
     [
       {                        (json object)
         "src": {               (json object) Source arguments
           "address": "str",    (string, required) Source address
           "amount": "str",     (string, required) Amount transfered, the value is amount in amount@token format
           "domain": n,         (numeric, required) Domain of source: 2 - DVM, 3 - EVM
           "data": "str",       (string) Optional data
         },
         "dst": {               (json object) Destination arguments
           "address": "str",    (string, required) Destination address
           "amount": "str",     (string, required) Amount transfered, the value is amount in amount@token format
           "domain": n,         (numeric, required) Domain of source: 2 - DVM, 3 - EVM
           "data": "str",       (string) Optional data
         },
       },
       ...
     ]

Result:
"hash"                  (string) The hex-encoded hash of broadcasted transaction

Examples:
> defi-cli transferdomain '[{"src":{"address":"<DFI_address>", "amount":"1.0@DFI", "domain": 2}, "dst":{"address":"<ETH_address>", "amount":"1.0@DFI", "domain": 3}}]'
> defi-cli transferdomain '[{"src":{"address":"<ETH_address>", "amount":"1.0@DFI", "domain": 3}, "dst":{"address":"<DFI_address>", "amount":"1.0@DFI", "domain": 2}}]'
```
