### ISSUE TITLE
Node shutdowns depending on snapshot

### ISSUE THREAD

**Issue by florianlindner** [DeFiCh/ain#3101] opened 2024-10-22 14:18 UTC
## Summary

Nodes shut down depending on the node version and snapshot version

## Steps to Reproduce

[Please use step-by bullet points to help the team reproduce the bug]

1. Startup node for example with:
`docker run -d --name n2 -p 86<xy>:85<xy> -v v2:/data --restart always defi/defichain:4.2.0 defid -rescan -vaultindex -txindex=1 -printtoconsole -rpcworkqueue=512 -rpcallowip=0.0.0.0/0 -rpcbind=0.0.0.0 -rpcauth='user:<xyz>$<xy’z>`

2. Depending on the snapshot the nodes will shutdown after each startup in a loop:
https://pastebin.com/XXdipmZU

The latest snapshot lead to different errors after a few hours of runtime:
_2024-10-22T21:20:24Z ERROR: ReadBlockFromDisk: OpenBlockFile failed for FlatFilePos(nFile=-1, nPos=0)_

## Environment

- Node Version: 4.2.0
- Block height on bug if applicable: LoadBlockIndexDB: last block file info: CBlockFileInfo(blocks=25838, size=114342959, heights=4397311...4422393, time=2024-10-06...2024-10-15)
- OS with version: Linux cr 4.15.0-202-generic 213-Ubuntu SMP Thu Jan 5 19:19:12 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
- Any other relevant environment info:  
The last tracked approach failed with an unfortunately unnamed snapshot named snapshot-mainnet-.tar.gz https://snapshot-de.mydefichain.com Depending on the node version and the snapshot the issue can be reproduced non deterministically. Latest approach with 4.2.0 and snapshot-mainnet-4268284.zip shows now shows a promising success rate.

**Comment by prasannavl** [comment] 2024-10-23 02:47
Thanks for the report @florianlindner. 

```
2024-10-20T23:19:22Z : Unable to get DVM block hash from latest EVM block hash, inconsistent chainstate detected. This may be due to corrupted block databases between DVM and EVM, and you will need to rebuild the database using -reindex..
Please restart with -reindex or -reindex-chainstate to recover.
: Unable to get DVM block hash from latest EVM block hash, inconsistent chainstate detected. This may be due to corrupted block databases between DVM and EVM, and you will need to rebuild the database using -reindex..
Please restart with -reindex or -reindex-chainstate to recover.
2024-10-20T23:19:22Z Aborted block database rebuild. Exiting.
```

 I think the messages state the problem - As the log messages indicate, these are the node's protection mechanism when it detect inconsistent data to ensure you are not running on corrupt data. 
 
 We do have visibility to external snapshots. I'd suggest reporting this to mydefichain.com as many community do rely on their snapshots. 
 
Before filing snapshot related bugs, I'd suggest trying a full sync, or snapshots that are provided the core team - we put in a lot of effort to verify integrity of these. 

The new RPC feature from the node `logdbhashes` can now help with verifying the consistent of the entire database of snapshots going forward from 4.2.0.

Glad to hear it's working now. Let us know if there's anything else. Or I'll go ahead and close this as I do not see anything action-able on our end here.

**Closed** 2024-10-23 10:53 UTC

**Comment by skutcher** [comment] 2024-10-24 15:21
@prasannavl  i think its not that easy and should remain open. It happens as well without docker and with the original snapshots.
As already mentioned in #3098 i started from https://defi-snapshots-europe.s3.eu-central-1.amazonaws.com/snapshot-mainnet-4268284.zip and now the fifth time in this week to have something like this
```
2024-10-24T14:07:43Z UpdateTip: height=4448608 hash=70a97135145106a6a1962ea5224982f3c022749201e55bf8ce0d33eb2b090410 date='2024-10-24T14:08:01Z' tx=34829281 log2_work=88.534738 progress=1.000000
2024-10-24T14:10:20Z UpdateTip: height=4448609 hash=f2b4636b549575b8cb4dc3ef33aabc00739328f2e079e3f55f91160178c38843 date='2024-10-24T14:10:44Z' tx=34829314 log2_work=88.534739 progress=1.000000
2024-10-24T14:10:29Z UpdateTip: height=4448610 hash=3e8bd3f805ea44939b626385641a3ae274713913bdc45fe9709dff69a29cff2f date='2024-10-24T14:08:05Z' tx=34829317 log2_work=88.534739 progress=0.999999
Killed
```

Afterwards i need again to sync from one of the older snapshots as mentioned in #3098, otherwise I see exact the same error as @florianlindner : 
```
2024-10-24T15:08:29Z Ignoring unknown configuration value rpcconnect
2024-10-24T15:08:29Z DeFi Blockchain version v4.2.0 (release build)
2024-10-24T15:08:29Z [ain_grpc] Init rs logging
2024-10-24T15:08:29Z conf: fd limit: req: 283, set 1024, max: 524288
2024-10-24T15:08:29Z conf: checkpoints enabled.
2024-10-24T15:08:29Z Assuming ancestors of block 9b257cb88630e422902ef2b17a3627ae2f786a5923df9c3bda4226f9551b1ea8 have valid signatures.
2024-10-24T15:08:29Z Setting nMinimumChainWork=000000000000000000000000000000000000000000003f2949bfe4efc275390c
2024-10-24T15:08:29Z Using the 'shani(1way,2way)' SHA256 implementation
2024-10-24T15:08:29Z Using RdSeed as additional entropy source
2024-10-24T15:08:29Z Using RdRand as an additional entropy source
2024-10-24T15:08:29Z Default data directory /home/user/.defi
2024-10-24T15:08:29Z Using data directory /home/user.defi/
2024-10-24T15:08:29Z Config file: /home/user/.defi/defi.conf
2024-10-24T15:08:29Z Using at most 125 automatic connections (1024 file descriptors available)
2024-10-24T15:08:29Z Using 16 MiB out of 32/2 requested for signature cache, able to store 524288 elements
2024-10-24T15:08:29Z Using 16 MiB out of 32/2 requested for script execution cache, able to store 524288 elements
2024-10-24T15:08:29Z conf: walletfastselect: false
2024-10-24T15:08:29Z conf: walletcoinoptskipsolvable: false
2024-10-24T15:08:29Z conf: walletcoinopteagerselect: false
2024-10-24T15:08:29Z Script verification uses 3 additional threads
2024-10-24T15:08:29Z scheduler thread start
2024-10-24T15:08:29Z WARNING: option -rpcbind was ignored because -rpcallowip was not specified, refusing to allow everyone to connect
2024-10-24T15:08:29Z Socket: RPC port bound to ::1:8554
2024-10-24T15:08:29Z Socket: RPC port bound to 127.0.0.1:8554
2024-10-24T15:08:29Z HTTP: creating work queue of depth 16
2024-10-24T15:08:29Z Config options rpcuser and rpcpassword will soon be deprecated. Locally-run instances may remove rpcuser to use cookie-based auth, or may be replaced with rpcauth. Please see share/rpcauth for rpcauth auth generation.
2024-10-24T15:08:29Z Using rpcauth authentication.
2024-10-24T15:08:29Z HTTP: starting 4 worker threads
2024-10-24T15:08:29Z Using wallet directory /home/user/.defi/
2024-10-24T15:08:29Z init message: Verifying wallet(s)...
2024-10-24T15:08:29Z Using BerkeleyDB version Berkeley DB 4.8.30: (April  9, 2010)
2024-10-24T15:08:29Z Using wallet /home/user/.defi/wallet.dat
2024-10-24T15:08:29Z BerkeleyEnvironment::Open: LogDir=/home/user/.defi/wallet.dat/database ErrorFile=/home/user/.defi/wallet.dat/db.log
2024-10-24T15:08:30Z init message: Loading banlist...
2024-10-24T15:08:30Z Cache configuration:
2024-10-24T15:08:30Z * Using 4.0 MiB for block index database
2024-10-24T15:08:30Z * Using 8.0 MiB for chain state database
2024-10-24T15:08:30Z * Using 500.0 MiB for in-memory UTXO set (plus up to 286.1 MiB of unused mempool space)
2024-10-24T15:08:30Z DfTxTaskPool: Init (0)
2024-10-24T15:08:30Z DfTxTaskPool: Size: 15
2024-10-24T15:08:30Z init message: Loading block index...
2024-10-24T15:08:30Z Opening LevelDB in /home/user/.defi/blocks/index
2024-10-24T15:08:30Z Opened LevelDB successfully
2024-10-24T15:08:30Z Using obfuscation key for /home/user/.defi/blocks/index: 0000000000000000
2024-10-24T15:08:45Z LoadBlockIndexDB: last block file = 117
2024-10-24T15:08:45Z LoadBlockIndexDB: last block file info: CBlockFileInfo(blocks=18153, size=127249658, heights=4430416...4448556, time=2024-10-18...2024-10-24)
2024-10-24T15:08:45Z Checking all blk files are present...
2024-10-24T15:08:45Z Opening LevelDB in /home/user/.defi/chainstate
2024-10-24T15:08:45Z Opened LevelDB successfully
2024-10-24T15:08:45Z Using obfuscation key for /home/user/.defi/chainstate: ed290cf9120cb16b
2024-10-24T15:08:45Z Opening LevelDB in /home/user/.defi/enhancedcs
2024-10-24T15:08:45Z Opened LevelDB successfully
2024-10-24T15:08:45Z Using obfuscation key for /home/user/.defi/enhancedcs: 0000000000000000
2024-10-24T15:08:45Z Opening LevelDB in /home/user/.defi/history
2024-10-24T15:08:45Z Opened LevelDB successfully
2024-10-24T15:08:45Z Using obfuscation key for /home/user/.defi/history: 0000000000000000
2024-10-24T15:08:45Z Opening LevelDB in /home/user/.defi/burn
2024-10-24T15:08:45Z Opened LevelDB successfully
2024-10-24T15:08:45Z Using obfuscation key for /home/user/.defi/burn: 0000000000000000
2024-10-24T15:08:45Z Opening LevelDB in /home/user/.defi/vault
2024-10-24T15:08:45Z Opened LevelDB successfully
2024-10-24T15:08:45Z Using obfuscation key for /home/user/.defi/vault: 0000000000000000
2024-10-24T15:08:45Z [ain_grpc] Init rs services
2024-10-24T15:08:45Z [ain_evm::evm] Initializating VSDB
2024-10-24T15:08:45Z [ain_evm::evm] VSDB directory : /home/user/.defi/evm/.vsdb
2024-10-24T15:08:47Z Loaded best chain: hashBestChain=3f0780af15310df018d59590dd5a0745b37fd1916eb74a183a81643176a8bd1d height=4446897 date=2024-10-23T23:40:11Z progress=0.999705
2024-10-24T15:08:47Z init message: Rewinding blocks...
2024-10-24T15:08:48Z init message: Verifying blocks...
2024-10-24T15:08:48Z Verifying last 6 blocks at level 3
2024-10-24T15:08:48Z [0%]...[16%]...[33%]...[50%]...[66%]...[83%]...[99%]...[DONE].
2024-10-24T15:08:48Z No coin database inconsistencies in last 6 blocks (6 transactions)
2024-10-24T15:08:48Z : Unable to get DVM block hash from latest EVM block hash, inconsistent chainstate detected. This may be due to corrupted block databases between DVM and EVM, and you will need to rebuild the database using -reindex..
Please restart with -reindex or -reindex-chainstate to recover.
: Unable to get DVM block hash from latest EVM block hash, inconsistent chainstate detected. This may be due to corrupted block databases between DVM and EVM, and you will need to rebuild the database using -reindex..
Please restart with -reindex or -reindex-chainstate to recover.
2024-10-24T15:08:48Z Aborted block database rebuild. Exiting.
2024-10-24T15:08:48Z Shutdown: In progress...
2024-10-24T15:08:48Z [ain_grpc] Shutdown rs network services
2024-10-24T15:08:48Z scheduler thread exit
2024-10-24T15:08:48Z DfTxTaskPool: Waiting for tasks
2024-10-24T15:08:48Z DfTxTaskPool: Shutdown
2024-10-24T15:08:48Z [ain_grpc] Shutdown rs services
2024-10-24T15:08:48Z Shutdown: done
```

**Comment by prasannavl** [comment] 2024-10-25 00:07
@skutcher - this is expected behavior. Once the data is corrupted, through
unclean shutdown of any form - be it a crash, manually killing it or OOM,
the node's integrity check will prevent it from proceeding. There is _some_
auto recovery built-in, but chances that it autorecovers are usually low,
due to some of the legacy storage layers in common with Bitcoin, and will
trip the switch in favor for safety and correctness and fail on startup
instead of running with inconsistent data.

**Comment by florianlindner** [comment] 2024-10-27 02:40
@prasannavl I am a bit sceptical as well. It doesn't matter which snaophot we use. I think we tried over 100.

There will always be the time when they disconnect. No matter what snapshot you take. Most of them after a few hours. Some after weeks. We are rnuning 6 nodes. No matter what we do. It will just not work if you just wait a certain amount of time. I am out of ideas. I cannot provide more then those error logs.

**Comment by Stonygan** [comment] 2024-10-27 06:50
ReadBlockFromDisk: OpenBlockFile failed for FlatFilePos(nFile=-1, nPos=0

This indicates a problem with to many open files. Please check ulimit -n how many simultaneous files are allowed. Default 1024 is not enough for the node.

**Comment by skutcher** [comment] 2024-10-27 09:35
Just figured out that there seems to be some memory peeks. Don't know atm
if that relates to this ticket but on my test system where more or less
only the node is running I had a peak so that 32gb of RAM where not enough
resulting in process kill. Maybe it's related to this wallet snapshot
feature?

Dr. Florian Lindner ***@***.***> schrieb am So., 27. Okt.
2024, 03:40:

**Comment by florianlindner** [comment] 2024-10-29 02:03
Thanks I could resolve the issue with the following setup:

1. Snapshot snapshot-mainnet-4455886.zip
2. Reduce number of node instances in the cluster from 6 top 3
3. Increase ulimit to 32768
4. Activate and increase swap memory.

For now everything totally smooth! Thanks again for jumping in.
